### ISSUE TITLE
Seems to have problems with big objects

### ISSUE THREAD

**Issue by Sainan** [robisonsantos/packfile_reader#2]
Hi, I'm presently working on a Git client type thing, and I'm using this as a reference. I'm testing against a relatively simple repository (https://github.com/calamity-inc/universal-analog-plugin), but the `wooting_analog_common.lib` file is relatively large, and it is here where packfile_reader seems to get stuck:

![image](https://github.com/user-attachments/assets/67b8e6a6-7bdf-4b69-a011-7da89532f078)

My implementation for reference:

![image](https://github.com/user-attachments/assets/5698e56f-4648-4a1e-90ed-c00a5cf920e8)

It may be useful to note that the compressed length is typically obvious from where the decompressor stopped, so you can just give it the entire remaining data and then see where it ended up (tho I'm not familiar with Ruby's bindings in particular):

![image](https://github.com/user-attachments/assets/c5209e56-313c-40d8-bec2-cd07f6218274)

**Comment by robisonsantos** [comment]
Thanks for reporting it. I'll take a look as soon as I have some time.

**Comment by robisonsantos** [comment]
I think this could work, but the problem is that I will need to have the whole packfile in memory. The `zlib` library needs an array of bytes to inflate, that means I'd need to read the whole file, store its bytes into an array and process it. Depending on the size of the repo, that can be a lot.

**Comment by Sainan** [comment]
People will have a few megs or even gigs of RAM to spare. But several minutes (maybe even hours, I didn't let it run for that long) just to parse a file... they probably won't have that to spare.

**Comment by robisonsantos** [comment]
You are probably right. I made it possible to pass a window size to the reader, so, if you know or suspect there are big blobs in the packfile, you can control how many bytes the tool uses to look for the data inside the file. In this way, I don't need to read the full packfile into memory, but people can still process it faster.

Example:


```
packfile_reader ../../universal-analog-plugin/.git/objects/pack/pack-7c0582703b8a61803433fa7fde52218644643964.pack -w 50_000
Packfile Headers
- Signature: PACK
- Version: 2
- Entries: 48

dd1b36033a2648083517d8e2978a28609e2902c3        OBJ_COMMIT      271
8350842c975b10d85b0625af430256564f2710fa        OBJ_COMMIT      219
48c2e73b838226fc374a3b46e66577f27d9b803c        OBJ_COMMIT      238
b41552980b6cf7b4c199e0d7ac58307f95f3b3fa        OBJ_COMMIT      236
62bc9c5247a5749ca93c238fcdff1a49732a3ce2        OBJ_COMMIT      169
53ef32d632325e8b18ef894deefb67e21868e8fb        OBJ_COMMIT      258
1caf9355dac9a5e6b1fbaab68eededabf0477493        OBJ_COMMIT      231
5d747bd0f36630001c1850d9faee0cde711666e2        OBJ_COMMIT      250
2f3cd82f4e3ff95f3bd501c98dfb86887fa8cbb9        OBJ_COMMIT      214
11a0b36e70c53445c837bd5881d4e0ed8cdd6a00        OBJ_COMMIT      224
644a60e433aa765aba99d551e2431dcd759a3634        OBJ_COMMIT      230
69610dd3cbe81bff1a5377315169631436f9b872        OBJ_COMMIT      268
4981d2ec303c502f711ef0a39763dd976ade6054        OBJ_COMMIT      286
37fe154cbcb53dcf110f8255295c1adbd6c67435        OBJ_COMMIT      252
bfe053c8fc65e5597605b541062d219df49ef42e        OBJ_TREE        196
329d66499ac3c31d7c67e1ae7e4cb8550241e07d        OBJ_TREE        196
5e8a5187518567f1aceb2e8a1cfa09d855ce7a8d        OBJ_TREE        143
85d80afc9e0cec7096f70214bf628e4377b3699c        OBJ_BLOB        50
8ab217967861221e6f89e0e39435c6a7fd838d8c        OBJ_BLOB        70
73cf64bad96fef53be919c8797227f6c8647ebac        OBJ_BLOB        1192
000     OBJ_OFS_DELTA   372
000     OBJ_OFS_DELTA   11
000     OBJ_OFS_DELTA   140
8f7b27d139f5c39c19606da4cf5f1dda07e32b97        OBJ_BLOB        5133
598495feb9e9a97fc808279a0cc03367331a7cff        OBJ_TREE        2110127
000     OBJ_OFS_DELTA   29
000     OBJ_OFS_DELTA   105
000     OBJ_OFS_DELTA   31
000     OBJ_OFS_DELTA   68
000     OBJ_OFS_DELTA   30
000     OBJ_OFS_DELTA   17
000     OBJ_OFS_DELTA   117
000     OBJ_OFS_DELTA   168
000     OBJ_OFS_DELTA   1008
000     OBJ_OFS_DELTA   22
964123f8c0f0b2fa40f77a5e8f946d648a111862        OBJ_BLOB        11942102
000     OBJ_OFS_DELTA   30
000     OBJ_OFS_DELTA   30
000     OBJ_OFS_DELTA   30
000     OBJ_OFS_DELTA   30
000     OBJ_OFS_DELTA   27
000     OBJ_OFS_DELTA   27
000     OBJ_OFS_DELTA   27
000     OBJ_OFS_DELTA   27
000     OBJ_OFS_DELTA   27
000     OBJ_OFS_DELTA   27
000     OBJ_OFS_DELTA   30
203ea983a395a1ae3865bce027ba541aab0ecd07        OBJ_BLOB        23
```

**Comment by Sainan** [comment]
Still kinda the same problem by default, but at least now `--window-size=10000000` can be used to speed it up:

![image](https://github.com/user-attachments/assets/81f0c415-bd0a-4ee7-a155-e65e2c6a8aed)

**Comment by robisonsantos** [comment]
That's the idea. Kind of a middle ground :)
